name: E2E Tests

permissions: {}

on:
  workflow_dispatch: {}
  pull_request:
    branches:
      - 'main'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  chainsaw:
    strategy:
      fail-fast: false
      matrix:
        k8s-version:
          - name: v1.25
            version: v1.25.16
          - name: v1.26
            version: v1.26.14
          - name: v1.27
            version: v1.27.11
          - name: v1.28
            version: v1.28.7
          - name: v1.29
            version: v1.29.2
        tests:
          - ^argo$
          - ^aws$
          - ^best-practices$
          - ^best-practices-cel$
          - ^castai$
          - ^cert-manager$
          - ^cleanup$
          - ^consul$
          - ^external-secret-operator$
          - ^flux$
          - ^istio$
          - ^karpenter$
          - ^kasten$
          - ^kubecost$
          - ^kubeops$
          - ^kubevirt$
          - ^linkerd$
          - ^nginx-ingress$
          - ^openshift$
          - ^other$/^a
          - ^other-cel$/^a
          - ^other$/^[b-d]
          - ^other-cel$/^[b-d]
          - ^other$/^[e-l]
          - ^other-cel$/^[e-l]
          - ^other$/^[m-q]
          - ^other-cel$/^[m-q]
          - ^other$/^re[c-q]
          - ^other-cel$/^re[c-q]
          - ^other$/^res
          - ^other-cel$/^res
          - ^other$/^[s-z]
          - ^other-cel$/^res
          - ^pod-security$
          - ^pod-security-cel$
          - ^psa$
          - ^psp-migration$
          # - ^tekton
          # - ^traefik
          # - ^velero
    runs-on: ubuntu-latest
    name: ${{ matrix.k8s-version.name }} - ${{ matrix.tests }}
    steps:
      - name: Checkout
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6
      - name: Setup Go
        uses: actions/setup-go@cdcb36043654635271a94b9a6d1392de5bb323a7 # v5.0.1
        with:
          go-version: ~1.21.1
      - name: Install Tools
        run: |
          set -e
          curl -LO "https://dl.k8s.io/release/${{ matrix.k8s-version.version }}/bin/linux/amd64/kubectl"
          sudo install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl
      - name: Install kind
        shell: bash
        run: |
          set -e
          # For AMD64 / x86_64
          [ $(uname -m) = x86_64 ] && curl -Lo ./kind https://kind.sigs.k8s.io/dl/v0.20.0/kind-linux-amd64
          # For ARM64
          [ $(uname -m) = aarch64 ] && curl -Lo ./kind https://kind.sigs.k8s.io/dl/v0.20.0/kind-linux-arm64
          chmod +x ./kind
          sudo mv ./kind /usr/local/bin/kind
      - name: Install latest Kyverno CLI
        uses: kyverno/action-install-cli@fcee92fca5c883169ef9927acf543e0b5fc58289 # v0.2.0
      - name: Create kind cluster
        run: |
          set -e
          kind create cluster --image kindest/node:${{ matrix.k8s-version.version }} --config ./.github/kind.yml
      - name: Install latest kyverno
        run: |
          set -e
          kubectl create -f https://github.com/kyverno/kyverno/raw/main/config/install-latest-testing.yaml
      - name: Wait for kyverno ready
        run: |
          set -e
          kubectl wait --namespace kyverno --for=condition=ready pod --selector '!job-name' --timeout=60s
      - name: Install CRDs
        run: |
          set -e
          kubectl apply -f ./.chainsaw/crds
      - name: Install Chainsaw
        uses: kyverno/action-install-chainsaw@ef2517389320aae0fd7c067aa14b060eef08b76d # v0.2.3
      - name: Test with Chainsaw
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -e
          chainsaw test --config .chainsaw.yaml --include-test-regex '^chainsaw$/${{ matrix.tests }}' --no-color=false
  
  validatingadmissionpolicies-v1alpha1:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        k8s-version:
          - name: v1.27
            version: v1.27.10
        tests:
          - ^pod-security-cel$
    name: ${{ matrix.k8s-version.name }} - validating-admission-policies - ${{ matrix.tests }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b # v4.1.5
      - name: Create kind cluster
        uses: helm/kind-action@0025e74a8c7512023d06dc019c617aa3cf561fde # v1.10.0
        with:
          node_image: kindest/node:${{ matrix.k8s-version.version }}
          cluster_name: kind
          config: ./.github/scripts/config/kind/vap-v1alpha1.yaml
      - name: Install latest kyverno with VAP generation enabled
        run: ./.github/scripts/config/generate-validating-admission-policy/install-kyverno.sh
      - name: Wait for kyverno ready
        run: |
          set -e
          kubectl wait --namespace kyverno --for=condition=ready pod --selector '!job-name' --timeout=60s
      - name: Install CRDs
        run: |
          set -e
          kubectl apply -f ./.chainsaw/crds
      - name: Install Chainsaw
        uses: kyverno/action-install-chainsaw@748066cc1580718e7924c9b689a8d366bde05100 # v0.2.0
      - name: Test with Chainsaw
        run: |
          set -e
          chainsaw test --config .chainsaw.yaml  --include-test-regex '^chainsaw$/${{ matrix.tests }}' --test-file='chainsaw-test-vap' --no-color=false
        
  k8s-version-specific-tests-above-1-28:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        k8s-version:
          - name: v1.28
            version: v1.28.7
          - name: v1.29
            version: v1.29.2
        tests:
          - ^pod-security-cel$
    name: ${{ matrix.k8s-version.name }} - validating-admission-policies - ${{ matrix.tests }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b # v4.1.5
      - name: Create kind cluster
        uses: helm/kind-action@0025e74a8c7512023d06dc019c617aa3cf561fde # v1.10.0
        with:
          node_image: kindest/node:${{ matrix.k8s-version.version }}
          cluster_name: kind
          config: ./.github/scripts/config/kind/vap-v1beta1.yaml
      - name: Install latest kyverno with VAP generation enabled
        run: ./.github/scripts/config/generate-validating-admission-policy/install-kyverno.sh
      - name: Wait for kyverno ready
        run: |
          set -e
          kubectl wait --namespace kyverno --for=condition=ready pod --selector '!job-name' --timeout=60s
      - name: Install CRDs
        run: |
          set -e
          kubectl apply -f ./.chainsaw/crds
      - name: Install Chainsaw
        uses: kyverno/action-install-chainsaw@748066cc1580718e7924c9b689a8d366bde05100 # v0.2.0
      - name: Test with Chainsaw
        run: |
          set -e
          chainsaw test --config .chainsaw.yaml  --include-test-regex '^chainsaw$/${{ matrix.tests }}' --test-file='chainsaw-test-vap' --no-color=false